package com.example.quizweb.exception;

public enum ErrorCode {

    // Auth
    AUTH_USERNAME_ALREADY_EXISTS,
    AUTH_INVALID_CREDENTIALS,
    AUTH_UNAUTHORIZED,
    AUTH_FORBIDDEN,

    // Quiz / Question
    QUIZ_NOT_FOUND,
    QUESTION_NOT_FOUND,
    QUIZ_FORBIDDEN,
    INVALID_QUESTION_DATA,

    // Room
    ROOM_NOT_FOUND,
    ROOM_ALREADY_FINISHED,
    ROOM_NOT_PLAYING,
    ROOM_ALREADY_STARTED,
    ROOM_INVALID_STATUS,

    // Player
    PLAYER_NAME_ALREADY_EXISTS,
    PLAYER_NOT_FOUND,
    PLAYER_NOT_IN_ROOM,

    // Answer / Game
    ANSWER_ALREADY_SUBMITTED,
    QUESTION_NOT_CURRENT,
    QUESTION_TIME_EXPIRED,
    GAME_NOT_STARTED,
    GAME_ALREADY_FINISHED,

    // System
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR
}